language: node_js
node_js: node
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
addons:
  firefox: '51.0'
deploy:
  provider: npm
  email: core@donejs.com
  api_key:
    secure: G0PsCrpYmyMrsvJ0Jogi6vUvy91qGUY6KwpaXVAfI9O1mIhYkrVUJujttrMHuMeFib9Se0HKTggA+ZfSJAwpG4RCs5yGadHubvuU13hgdTtGmzKlq09LtTaGLLjjkzN2EV5UMuVXfMvnMXBruMyHw3o3hAeUJliH8i9pJbQApbU7MRtmWpKjk5e+CnGwknKY2IpkRDV5hhEtf5+gLSBxkODn3dMquz3T3LXmrXKlxF5K6ixGGqDyEe+YLA2Nu0FYY40PQyFgzzpc+3vQlfrTUxUgphjMXMSAXSvETc2Wv465cWYYNwKFoq9uzy8NogWwHoN4m6X0dTaOA2TrZ0EOXe4go+eA0bjYhszwwX/5pnF+8i76l2oCkURNxJaA+HhfS/cW2Q+n9FhfRf6WbzftT9/Bh759SOk2EbFXWLxRXp6wABqLpAULqtnEhmxt7Adqwisci42CL+boTSMgCpVN1L4NoYQKMzylSBj8QWMsjj6f790PtIw6m5JZVvCMM07277J5M7fhGkCF6Dn29MH/jOm7YZoGokOF6bYiwnB7jfQe02+BO2CmhCtfLfwPu9nspGbVBcTvRE/yjjKxNYvjLcLlEGLOGIAjk/2xQXfCXvM/VInn208Ewf0YwPlyI8Km2tgogb/1kV0m9zH/eqdI42otuyhuzsudT/S5jtuFa/s=
  on:
    tags: true
    repo: canjs/can-model
